-- Run in Supabase SQL Editor (Dashboard → SQL → New query).
-- The local-runtime uses the service role key server-side only; it bypasses RLS.

create table if not exists public.tutor_chat_turns (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null,
  student_name text not null,
  concept_id text not null,
  session_key text not null,
  layer text not null,
  age_group text not null,
  tutor_trigger text not null,
  user_message text not null,
  assistant_reply text not null,
  from_cache boolean not null default false,
  model_id text not null default 'claude-sonnet-4-6',
  history_message_count integer not null default 0
);

create index if not exists idx_tutor_chat_turns_created on public.tutor_chat_turns (created_at desc);
create index if not exists idx_tutor_chat_turns_student on public.tutor_chat_turns (student_name);
create index if not exists idx_tutor_chat_turns_session on public.tutor_chat_turns (session_key);

create table if not exists public.tutor_evaluation_turns (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null,
  student_name text not null,
  concept_id text not null,
  session_key text not null,
  layer text not null,
  age_group text not null,
  drawing_prompt text not null,
  path_count integer not null,
  result_json jsonb not null,
  from_cache boolean not null default false,
  model_id text not null default 'claude-sonnet-4-6'
);

create index if not exists idx_tutor_eval_turns_created on public.tutor_evaluation_turns (created_at desc);
create index if not exists idx_tutor_eval_turns_student on public.tutor_evaluation_turns (student_name);

create table if not exists public.tutor_session_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null,
  event_type text not null,
  student_name text not null,
  detail text
);

create index if not exists idx_tutor_session_events_created on public.tutor_session_events (created_at desc);

-- Optional: revoke public access; backend uses service role only.
-- alter table public.tutor_chat_turns enable row level security;
-- (Service role still inserts; anon should have no grants.)
